from const.data_element import DataElementTuple

# https://expediagroup.atlassian.net/wiki/spaces/EDMG/pages/478642776/EDMG+-+Tags+for+Data+Governance
# https://expediagroup.atlassian.net/wiki/spaces/ExGS/pages/593272951/Expedia+Group+Information+Classification+Policy

data_elements = [
    {
        "tuple": DataElementTuple(
            name="Email Address",
            type="String",
            description="Email address used for EG customers (travelers, owners, etc).",
            properties={
                "Classification": "Confidential",
            },
        ),
        "keys": [
            "email",
            "email address",
            "email alias",
            "email domain",
            "passport email",
            "recipient_email_address",
            "recipient email address",
        ],
    },
    {
        "tuple": DataElementTuple(
            name="Address",
            type="String",
            description="Address, or part of an address. Number, street, city, state/province, postal code, county, region, country, latitude/longitude",
            properties={
                "Classification": "Confidential",
            },
        ),
        "keys": [
            "address",
            "street",
            "city",
            "state",
            "country" "postalcode",
            "mailingaddress",
            "mailingstreet",
            "mailingcity",
            "mailingcity",
            "mailingstate",
            "mailingpostalcode",
            "mailingcounty",
            "mailinglatitude",
            "mailinglongitude",
            "mailinggeocodeaccuracy",
            "otheraddress",
            "otherstreet",
            "othercity",
            "otherstate",
            "otherpostalcode",
            "othercountry",
            "otherlatitude",
            "otherlongitude",
            "othergeocodeaccuracy",
        ],
    },
    {
        "tuple": DataElementTuple(
            name="Date of Birth",
            type="String",
            description="Full date of birth of a person.",
            properties={
                "Classification": "Sensitive",
            },
        ),
        "keys": ["birthdate", "birth date", "dob"],
    },
    {
        "keys": [
            "device id",
        ],
        "tuple": DataElementTuple(
            name="Device ID",
            type="String",
            description="Non-EG-specific identifier of device (MAC address, IMEI number of cell phones, Dell Service ID, IP address, IDFA, IDFV, AAID, DUIAD, Adobe's Visitor ID, Firebase App Identifier, etc)",
            properties={
                "Classification": "Confidential",
            },
        ),
    },
    {
        "tuple": DataElementTuple(
            name="EG-Internal User ID",
            type="String",
            description="""
            Traveler ID, user ID, Loyalty number that has no meaning outside of EG systems i.e. it is generated by EG and/or affiliates/partners.

            Note: If another EG proprietary dataset is needed to map the internal ID to an actual user, then the EG-Internal User ID is not considered PII.  The following are examples that are not considered PII:  Visitor_ID, Conversations_ID, Booking_ID
            """,
            properties={
                "Classification": "Confidential",
            },
        ),
        "keys": ["eg-internal user id"],
    },
    {
        "keys": [
            "financial id",
        ],
        "tuple": DataElementTuple(
            name="Financial ID",
            type="String",
            description="""
            Traveler ID, user ID, Loyalty number that has no meaning outside of EG systems i.e. it is generated by EG and/or affiliates/partners.

            Note: If another EG proprietary dataset is needed to map the internal ID to an actual user, then the EG-Internal User ID is not considered PII.  The following are examples that are not considered PII:  Visitor_ID, Conversations_ID, Booking_ID
            """,
            properties={
                "Classification": "Highly Sensitive",
            },
        ),
    },
    {
        "keys": [
            "gender",
        ],
        "tuple": DataElementTuple(
            name="Gender",
            type="String",
            description="Gender, sex, sexual orientation, or activity",
            properties={
                "Classification": "Sensitive",
            },
        ),
    },
    {
        "keys": [
            "government id",
        ],
        "tuple": DataElementTuple(
            name="Government ID",
            type="String",
            description="All government issued ID numbers excluding SSN. This includes DL, Tax ID, VAT/GST ID, and Passport No.",
            properties={
                "Classification": "Sensitive",
            },
        ),
    },
    {
        "keys": [
            "hs government id",
        ],
        "tuple": DataElementTuple(
            name="Highly Sensitive Government ID",
            type="String",
            description="Social Security Number (SSN). Data that is tagged Highly Sensitive should not enter EGDP",
            properties={
                "Classification": "Highly Sensitive",
            },
        ),
    },
    {
        "keys": [
            "last four credit card",
        ],
        "tuple": DataElementTuple(
            name="Last Four Credit Card",
            type="String",
            description="Last four digits of a travelers/partners credit card.",
            properties={
                "Classification": "Confidential",
            },
        ),
    },
    {
        "tuple": DataElementTuple(
            name="Name",
            type="String",
            description="Name of a person. Legal name, surname, etc",
            properties={
                "Classification": "Confidential",
            },
        ),
        "keys": [
            "name",
            "firstname",
            "lastname",
            "first name",
            "last name",
            "contact full name",
        ],
    },
    {
        "tuple": DataElementTuple(
            name="Phone",
            type="String",
            description="Phone number. Home, mobile, fax, text, work, etc",
            properties={
                "Classification": "Confidential",
            },
        ),
        "keys": [
            "phone",
            "phone number",
            "phone extension",
            "phone area code",
            "phone country code",
            "mobilephone",
            "fax",
        ],
    },
    {
        "tuple": DataElementTuple(
            name="Username",
            type="String",
            description="Login name used for EG customers (travelers, owners, etc). ",
            properties={
                "Classification": "Confidential",
            },
        ),
        "keys": ["username"],
    },
    {
        "tuple": DataElementTuple(
            name="User Generated Content",
            type="String",
            description="Comments, free text user-related information collected that falls out of the scope of the other tags, reviews completed by customers, survey responses, etc.",
            properties={
                "Classification": "Confidential",
            },
        ),
        "keys": ["user generated content"],
    },
]


def find_data_element(key: str):
    """
    Find a matching data element by key.
    """
    for data_element in data_elements:
        if key.lower() in data_element["keys"]:
            return data_element["tuple"]
    return None
