# Make sure this is consistent with mysql part of docker-compose.yml
FLASK_SECRET_KEY: SOME_RANDOM_SECRET_KEY

DATABASE_CONN: mysql+pymysql://test:passw0rd@mysql:3306/querybook2?charset=utf8mb4
REDIS_URL: redis://redis:6379/0
ELASTICSEARCH_HOST: http://elasticsearch:9200
# ELASTICSEARCH_CONNECTION_TYPE: aws
# Uncomment for email
# EMAILER_CONN: dockerhostforward

# Uncomment below to enable AI Assistant for local development.
# AI_ASSISTANT_PROVIDER: openai
# AI_ASSISTANT_CONFIG:
#     default:
#         model_args:
#             model_name: gpt-4o-mini
#             temperature: 0
#         reserved_tokens: 1024
#     table_summary:
#         model_args:
#             model_name: gpt-4o-mini
#             temperature: 0
#     sql_summary:
#         model_args:
#             model_name: gpt-4o-mini
#             temperature: 0
#     table_select:
#         model_args:
#             model_name: gpt-4o-mini
#             temperature: 0
#     sql_complete:
#         model_args:
#             model_name: gpt-4o-mini
#             temperature: 0

# Uncomment below to enable vector store to support embedding based table search.
# Please check langchain doc for the configs of each provider.
# EMBEDDINGS_PROVIDER: openai
# EMBEDDINGS_CONFIG: ~
# VECTOR_STORE_PROVIDER: opensearch
# VECTOR_STORE_CONFIG:
#     embeddings_arg_name: 'embedding_function'
#     opensearch_url: http://elasticsearch:9200
#     index_name: 'vector_index_v1'

#############
# EG Custom #
#############

# #
# # AI Assistant: Azure OpenAI
# #
AI_ASSISTANT_PROVIDER: azure_openai
AI_ASSISTANT_CONFIG:
    default:
        model_args:
            model_name: gpt-35-turbo-0125
            temperature: 0.2
            streaming: False
    sql_fix:
        model_args:
            model_name: gpt-4o-2024-05-13
            temperature: 0.2
            streaming: False
    sql_title:
        model_args:
            model_name: gpt-4o-2024-05-13
            temperature: 0.7
            streaming: False
    text_to_sql:
        model_args:
            model_name: gpt-4o-2024-05-13
            temperature: 0.2
            streaming: False

#
# Vector Store: Elasticsearch 8.x
#
VECTOR_STORE_PROVIDER: elasticsearch
VECTOR_STORE_CONFIG:
    embeddings_arg_name: 'embedding'
    es_url: http://vectorstore:9200
    index_name: 'vector_index_v1'

#
# Vector Store Embeddings: Azure OpenAI
# Note: use `openai` provider for Azure OpenAI due to proxy shenanigans
# eg_openai is an override that only sends text content to the model
#
EMBEDDINGS_PROVIDER: eg_openai
EMBEDDINGS_CONFIG:
    model: text-embedding-3-small
    chunk_size: 4096
# #
# # Vector Store Embeddings: Sentence Transformers
# # This is a tiny 80MB model
# # Requires `sentence-transformers` and `langchain-community` to be installed
# # https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2
# #
# EMBEDDINGS_PROVIDER: sentence_transformers
# EMBEDDINGS_CONFIG:
#     model_name: all-MiniLM-L6-v2

# #
# # Vector Store Embeddings: BGE
# # This is a tiny 134MB model
# # Requires `sentence-transformers` and `langchain-community` to be installed
# # https://huggingface.co/BAAI/bge-small-en-v1.5
# #
# EMBEDDINGS_PROVIDER: bge
# EMBEDDINGS_CONFIG:
#     model_name: BAAI/bge-small-en-v1.5
#     model_kwargs: { 'device': 'cpu' }
#     encode_kwargs: { 'normalize_embeddings': true }

# #
# # AI Assistant: Ollama
# # This is a local LLM server
# # Start using `docker compose run --service-ports ollama`
# # https://ollama.ai/
# #
# AI_ASSISTANT_PROVIDER: ollama
# OLLAMA_BASE_URL: http://ollama:11434
# AI_ASSISTANT_CONFIG:
#     default:
#         model_args:
#             model_name: tinydolphin:latest
#             temperature: 0.1
#             streaming: False
#         reserved_tokens: 1024
