"""Extend DataTableColumn type length (again)

Revision ID: 27ed76f75108
Revises: 1b8aba201c94
Create Date: 2023-03-16 09:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "27ed76f75108"
down_revision = "1b8aba201c94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_table_column",
        "type",
        nullable=True,
        existing_type=sa.String(length=4096),
        type_=sa.Text(length=32768),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_table_column",
        "type",
        nullable=True,
        existing_type=sa.Text(length=32768),
        type_=sa.String(length=4096),
    )
    # ### end Alembic commands ###
