"""Extend DataTableColumn type length

Revision ID: 27ed76f75107
Revises: 27ed76f75106
Create Date: 2022-12-14 15:42:06.639449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "27ed76f75107"
down_revision = "27ed76f75106"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_table_column",
        "type",
        nullable=True,
        existing_type=sa.String(length=1024),
        type_=sa.String(length=4096),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_table_column",
        "type",
        nullable=True,
        existing_type=sa.String(length=4096),
        type_=sa.String(length=1024),
    )
    # ### end Alembic commands ###
