"""add data catalog support

Revision ID: 56f99f47af3f
Revises: e7a17a8acf4c
Create Date: 2025-12-08 06:52:14.431748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56f99f47af3f'
down_revision = 'e7a17a8acf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'data_catalog',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(length=16777215), nullable=True),
        sa.Column('metastore_id', sa.Integer(), nullable=False),
        sa.Column('owner', sa.String(length=255), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('properties', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['metastore_id'], ['query_metastore.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('metastore_id', 'name', name='idx_catalog_metastore_name'),
        mysql_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_data_catalog_name'), 'data_catalog', ['name'], unique=False)
    op.add_column('data_schema', sa.Column('catalog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data_schema', 'data_catalog', ['catalog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_schema', type_='foreignkey')
    op.drop_column('data_schema', 'catalog_id')
    op.drop_index(op.f('ix_data_catalog_name'), table_name='data_catalog')
    op.drop_table('data_catalog')
    # ### end Alembic commands ###
