"""add promotion tables

Revision ID: 66a88534c7dc
Revises: abc123def456
Create Date: 2026-07-17 21:20:47.782245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66a88534c7dc'
down_revision = 'abc123def456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_datadoc_id', sa.Integer(), nullable=False),
    sa.Column('target_datadoc_id', sa.Integer(), nullable=True),
    sa.Column('source_environment_id', sa.Integer(), nullable=False),
    sa.Column('target_environment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'MERGING', 'PUBLISHED', 'REJECTED', 'FAILED', name='promotionstatus'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.String(length=5000), nullable=True),
    sa.Column('github_pr_url', sa.String(length=2083), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_datadoc_id'], ['data_doc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_environment_id'], ['environment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_datadoc_id'], ['data_doc.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_environment_id'], ['environment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_promotion_request_status'), 'promotion_request', ['status'], unique=False)
    op.create_table('promotion_reviewer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_request_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promotion_request_id'], ['promotion_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_request_id', 'uid', name='unique_promotion_reviewer'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.add_column('data_doc', sa.Column('promoted_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_data_doc_promoted_from_id', 'data_doc', 'data_doc', ['promoted_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_data_doc_promoted_from_id', 'data_doc', type_='foreignkey')
    op.drop_column('data_doc', 'promoted_from_id')
    op.drop_table('promotion_reviewer')
    op.drop_index(op.f('ix_promotion_request_status'), table_name='promotion_request')
    op.drop_table('promotion_request')
    # ### end Alembic commands ###
