"""add partition keys

Revision ID: 7f368cb1c51b
Revises: 2f40b8318af4
Create Date: 2022-08-19 17:13:50.930313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

#
# Resolved migration conflict manually
# From f449a73c5838 to 2f40b8318af4
#

# revision identifiers, used by Alembic.
revision = "7f368cb1c51b"
down_revision = "2f40b8318af4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_information', sa.Column('column_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_table_information', 'column_info')
    # ### end Alembic commands ###
