"""Added execute column to data_doc_editor

Revision ID: bb123456789a
Revises: aa328ae9dced
Create Date: 2025-08-08 21:49:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb123456789a"
down_revision = "aa328ae9dced"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_doc_editor', sa.Column('execute', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_doc_editor', 'execute')
    # ### end Alembic commands ###
