"""QueryExecution index on status

Revision ID: c50cef3b4a00
Revises: 4c70dae378f2
Create Date: 2023-09-23 14:17:15.156913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c50cef3b4a00"
down_revision = "4c70dae378f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_query_execution_status"), "query_execution", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_execution_status"), table_name="query_execution")
    # ### end Alembic commands ###
