import React from 'react';

import { IDataTable } from 'const/metastore';
import { Icon } from 'ui/Icon/Icon';
import { Markdown } from 'ui/Markdown/Markdown';
import { Message } from 'ui/Message/Message';
import { AccentText, EmptyText } from 'ui/StyledText/StyledText';

import './DataTableViewPumaInsights.scss';
import { Link } from 'ui/Link/Link';

interface IProps {
    table: IDataTable;
}

export const DataTableViewPumaInsights: React.FC<IProps> = ({ table }) => {
    if (
        !table.custom_properties ||
        (!table.custom_properties['table_purpose'] &&
            !table.custom_properties['business_value'] &&
            !table.custom_properties['key_characteristics'])
    ) {
        return (
            <EmptyText className="m24">
                No PUMA Insights have been generated for this table.
            </EmptyText>
        );
    }

    const tablePurposeMarkdown =
        table.custom_properties['table_purpose'] ||
        'No table purpose provided.';

    const businessValueMarkdown =
        table.custom_properties['business_value'] ||
        'No business value provided.';

    const keyCharacteristicsMarkdown =
        table.custom_properties['key_characteristics'] ||
        'No key characteristics provided.';

    const AITooltipTitle = (title: string) => (
        <AccentText size="med" color="text" weight="bold" className="mt16">
            <span
                aria-label="AI Generated Content from PUMA"
                data-balloon-pos="right"
            >
                <Icon name="Stars" size={16} />
            </span>{' '}
            {title}
        </AccentText>
    );

    return (
        <div className="DataTableViewPumaInsights">
            <Message icon="Info" iconSize={16} type="info">
                PUMA (Platform Usage Metrics and Analytics) is a data product to
                track usage across different tools under EGAP.{' '}
                <Link
                    newTab
                    to="https://expediagroup.atlassian.net/wiki/spaces/DSPKB/pages/393151452/PUMA"
                >
                    Check out the KB here
                </Link>
            </Message>

            <Message
                icon="AlertTriangle"
                iconSize={16}
                message="The content below is generated by AI and may not be accurate."
                type="warning"
            />

            {AITooltipTitle('Table Purpose')}
            <Markdown>{tablePurposeMarkdown as string}</Markdown>
            {AITooltipTitle('Business Value')}

            {/* // Ignore underscores as formatting since table-name underscores are */}
            {/* not always inside backtick phrases */}
            <Markdown
                options={{
                    overrides: {
                        em: {
                            component: ({ children }) => <>_{children}_</>,
                        },
                    },
                }}
            >
                {businessValueMarkdown as string}
            </Markdown>
            {AITooltipTitle('Key Characteristics')}
            <Markdown>{keyCharacteristicsMarkdown as string}</Markdown>
        </div>
    );
};
