name: Publish Docker
on:
    push:

env:
    REGISTRY: egdataplatform-docker-internal-local.artylab.expedia.biz
    IMAGE_NAME: egdp-querybook

jobs:
    publish-docker:
        name: Push Docker image
        runs-on: eg-default

        steps:
            - name: Checkout ${{ github.event.release.tag_name }}
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.release.tag_name }}

            - name: Log into registry ${{ env.REGISTRY }}
              uses: actions/docker-login-action@v1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.ARTYLAB_USER }}
                  password: ${{ secrets.ARTYLAB_PASS }}

            - name: Setup Docker Buildx
              uses: actions/docker-setup-buildx-action@v1
              with:
                  driver: docker

            - name: Get version from package.json
              run: |
                  PATCH_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')
                  MINOR_VERSION=${PATCH_VERSION%.*}
                  MAJOR_VERSION=${MINOR_VERSION%.*}

                  echo PATCH_VERSION=$PATCH_VERSION >> $GITHUB_ENV
                  echo MINOR_VERSION=$MINOR_VERSION >> $GITHUB_ENV
                  echo MAJOR_VERSION=$MAJOR_VERSION >> $GITHUB_ENV

            - name: Docker metadata
              uses: actions/docker-metadata-action@v3
              id: meta
              with:
                  images: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  flavor: |
                      latest=true
                  tags: |
                      type=raw,value=${{ env.PATCH_VERSION }},enable=${{ github.ref_name == 'master' }}
                      type=raw,value=${{ env.MINOR_VERSION }},enable=${{ github.ref_name == 'master' }}
                      type=raw,value=${{ env.MAJOR_VERSION }},enable=${{ github.ref_name == 'master' }}
                      type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short,enable=,enable=${{ github.ref_name != 'master' }}

            - name: Docker build
              uses: actions/docker-build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      EXTRA_PIP_INSTALLS=extra.txt
