name: NodeTests
on:
    push:
        branches:
            - master
        paths:
            - 'querybook/**/*.jsx?'
            - 'querybook/**/*.tsx?'
            - 'querybook/**/*.s?css'
            - 'querybook/**/*.html'
            - 'package.json'
    pull_request:
        paths:
            - 'querybook/**/*.jsx?'
            - 'querybook/**/*.tsx?'
            - 'querybook/**/*.s?css'
            - 'querybook/**/*.html'
            - 'package.json'
jobs:
    nodetests:
        runs-on: eg-default
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - run: yarn install --frozen-lockfile --prefer-offline
            - run: ./querybook/scripts/run_test --node
