name: PythonTests
on:
    push:
        branches:
            - master
        paths:
            - '**.py'
    pull_request:
        paths:
            - '**.py'
jobs:
    pythontests:
        runs-on: eg-default
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/base.txt
                  pip install -r requirements/test.txt
            - run: PYTHONPATH=querybook/server ./querybook/scripts/run_test --python
