hints:
    - 'Format your queries by hovering over ⋮ and clicking on "Format Query".'
    - 'Change your editor theme in user settings under user icon on the bottom of the left sidebar.'
    - 'Running a long query? Click on "notify me" to be notified through email/slack on completion.'
    - 'Query not running? Check the status of the query engine on the bottom of the left sidebar.'
    - 'Use ⌘ K to search Docs/Tables.'
    - 'Need to collaborate on a DataDoc? Click the "Share" icon on top right to give access.'
    - 'Press shift + enter to launch queries quickly.'
    - 'Use ⌘S to force save DataDocs'
    - 'Organize your work using Lists, which can contain DataDocs, Query Executions, Tables, and other Lists.'
    - 'Add your team Security Group to DataDocs to easily share with your entire team.  Follow the [onboarding guide](https://confluence.expedia.biz/display/DSPKB/Adding+User+Groups+to+Querybook) to get started.'
    - 'Periodically review your scheduled DataDocs to ensure they are still relevant. Disable any that are no longer needed to save resources.'
    - 'Try the AI Assistant to help you write or edit queries. Click on the AI icon next to any DataDoc cell to get started.'
