# --------------- AI Assistant ---------------
ai_assistant:
    enabled: true

    query_title_generation:
        enabled: true

    query_generation:
        enabled: true

    query_auto_fix:
        enabled: true
