# Public Configs are shared between backend and frontend and are not sensitive
# --------------- AI Assistant ---------------
ai_assistant:
    enabled: true

    query_title_generation:
        enabled: true

    query_generation:
        enabled: true

    query_auto_fix:
        enabled: true

    table_vector_search:
        enabled: true

    query_vector_search:
        enabled: true

    sql_complete:
        enabled: true

survey:
    global_response_cooldown: 432000 # 5 days
    global_trigger_cooldown: 14400 # 4 hours
    global_trigger_duration: 60 # 1 minute
    global_max_per_week: 12
    global_max_per_day: 3

    surfaces:
        - surface: table_search
          max_per_week: 6
          max_per_day: 2
        - surface: table_view
          response_cooldown: 14400 # 4 hours
          max_per_week: 25
          max_per_day: 10
        - surface: text_to_sql
          response_cooldown: 1800 # 30 minutes
          trigger_cooldown: 900 # 15 minutes
          max_per_week: 35
          max_per_day: 10
        - surface: query_authoring
          response_cooldown: 1209600 # 14 days
          trigger_cooldown: 86400 # 24 hours
          max_per_week: 1

    # Uncomment to enable survey on all surfaces
    # surfaces:
    #     - surface: table_search
    #     - surface: table_view
    #     - surface: text_to_sql
    #     - surface: query_authoring

table_sampling:
    enabled: false
    sample_rates:
        - 0.1
    default_sample_rate: 0 # 0 means no sampling
    sample_user_guide_link: ''
    sampling_tool_tip_delay: 10000 # delay duration (ms) of sampling tool tip

github_integration:
    enabled: true
